/* eslint-disable */
export const mockResponseRecipes = {
  drinks: 
    [
      { strDrink: "Apple Cider Punch #1", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg", idDrink: "12864" },
      { strDrink: "Chocolate Monkey", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/tyvpxt1468875212.jpg", idDrink: "15615" },
      { strDrink: "Egg Nog #4", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/wpspsy1468875747.jpg", idDrink: "12910" },
      { strDrink: "Egg Nog - Healthy", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/qxuppv1468875308.jpg", idDrink: "12916" },
      { strDrink: "Egg-Nog - Classic Cooked", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/quxsvt1468875505.jpg", idDrink: "12914" },
      { strDrink: "GG", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg", idDrink: "15997" },
      { strDrink: "Gluehwein", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/vuxwvt1468875418.jpg", idDrink: "12944" },
      { strDrink: "Sunny Holiday Punch", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/rywtwy1468924758.jpg", idDrink: "13042" },
      { strDrink: "Wine Cooler", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/yutxtv1473344210.jpg", idDrink: "13056" }
    ]
}

export const mockRecipeArray = [
  { strDrink: "Apple Cider Punch #1", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg", idDrink: "12864" },
  { strDrink: "Chocolate Monkey", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/tyvpxt1468875212.jpg", idDrink: "15615" },
  { strDrink: "Egg Nog #4", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/wpspsy1468875747.jpg", idDrink: "12910" },
  { strDrink: "Egg Nog - Healthy", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/qxuppv1468875308.jpg", idDrink: "12916" },
  { strDrink: "Egg-Nog - Classic Cooked", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/quxsvt1468875505.jpg", idDrink: "12914" },
  { strDrink: "GG", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg", idDrink: "15997" },
  { strDrink: "Gluehwein", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/vuxwvt1468875418.jpg", idDrink: "12944" },
  { strDrink: "Sunny Holiday Punch", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/rywtwy1468924758.jpg", idDrink: "13042" },
  { strDrink: "Wine Cooler", strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/yutxtv1473344210.jpg", idDrink: "13056" }
]

export const mockRecipeDetails = {
  drinks: 
    [
      {
        idDrink: "12864",
        strDrink: "Apple Cider Punch #1",
        strVideo: null,
        strCategory: "Punch / Party Drink",
        strIBA: null,
        strAlcoholic: "Optional alcohol",
        strGlass: "Collins Glass",
        strInstructions: "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
        strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
        strIngredient1: "Apple cider",
        strIngredient2: "Brown sugar",
        strIngredient3: "Lemonade",
        strIngredient4: "Orange juice",
        strIngredient5: "Cloves",
        strIngredient6: "Allspice",
        strIngredient7: "Nutmeg",
        strIngredient8: "Cinnamon",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strMeasure1: "4 qt ",
        strMeasure2: "1 cup ",
        strMeasure3: "6 oz frozen ",
        strMeasure4: "6 oz frozen ",
        strMeasure5: "6 whole ",
        strMeasure6: "6 whole ",
        strMeasure7: "1 tsp ground ",
        strMeasure8: "3 sticks ",
        strMeasure9: " ",
        strMeasure10: " ",
        strMeasure11: " ",
        strMeasure12: " ",
        strMeasure13: " ",
        strMeasure14: "",
        strMeasure15: "",
        dateModified: "2016-02-03 15:26:58"
      },
      {
        idDrink: "12864",
        strDrink: "Apple Cider Punch #1",
        strVideo: null,
        strCategory: "Punch / Party Drink",
        strIBA: null,
        strAlcoholic: "Optional alcohol",
        strGlass: "Collins Glass",
        strInstructions: "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
        strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
        strIngredient1: "Apple cider",
        strIngredient2: "Brown sugar",
        strIngredient3: "Lemonade",
        strIngredient4: "Orange juice",
        strIngredient5: "Cloves",
        strIngredient6: "Allspice",
        strIngredient7: "Nutmeg",
        strIngredient8: "Cinnamon",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strMeasure1: "4 qt ",
        strMeasure2: "1 cup ",
        strMeasure3: "6 oz frozen ",
        strMeasure4: "6 oz frozen ",
        strMeasure5: "6 whole ",
        strMeasure6: "6 whole ",
        strMeasure7: "1 tsp ground ",
        strMeasure8: "3 sticks ",
        strMeasure9: " ",
        strMeasure10: " ",
        strMeasure11: " ",
        strMeasure12: " ",
        strMeasure13: " ",
        strMeasure14: "",
        strMeasure15: "",
        dateModified: "2016-02-03 15:26:58"
      },
      {
        idDrink: "12864",
        strDrink: "Apple Cider Punch #1",
        strVideo: null,
        strCategory: "Punch / Party Drink",
        strIBA: null,
        strAlcoholic: "Optional alcohol",
        strGlass: "Collins Glass",
        strInstructions: "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
        strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
        strIngredient1: "Apple cider",
        strIngredient2: "Brown sugar",
        strIngredient3: "Lemonade",
        strIngredient4: "Orange juice",
        strIngredient5: "Cloves",
        strIngredient6: "Allspice",
        strIngredient7: "Nutmeg",
        strIngredient8: "Cinnamon",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strMeasure1: "4 qt ",
        strMeasure2: "1 cup ",
        strMeasure3: "6 oz frozen ",
        strMeasure4: "6 oz frozen ",
        strMeasure5: "6 whole ",
        strMeasure6: "6 whole ",
        strMeasure7: "1 tsp ground ",
        strMeasure8: "3 sticks ",
        strMeasure9: " ",
        strMeasure10: " ",
        strMeasure11: " ",
        strMeasure12: " ",
        strMeasure13: " ",
        strMeasure14: "",
        strMeasure15: "",
        dateModified: "2016-02-03 15:26:58"
      },
      {
        idDrink: "12864",
        strDrink: "Apple Cider Punch #1",
        strVideo: null,
        strCategory: "Punch / Party Drink",
        strIBA: null,
        strAlcoholic: "Optional alcohol",
        strGlass: "Collins Glass",
        strInstructions: "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
        strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
        strIngredient1: "Apple cider",
        strIngredient2: "Brown sugar",
        strIngredient3: "Lemonade",
        strIngredient4: "Orange juice",
        strIngredient5: "Cloves",
        strIngredient6: "Allspice",
        strIngredient7: "Nutmeg",
        strIngredient8: "Cinnamon",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strMeasure1: "4 qt ",
        strMeasure2: "1 cup ",
        strMeasure3: "6 oz frozen ",
        strMeasure4: "6 oz frozen ",
        strMeasure5: "6 whole ",
        strMeasure6: "6 whole ",
        strMeasure7: "1 tsp ground ",
        strMeasure8: "3 sticks ",
        strMeasure9: " ",
        strMeasure10: " ",
        strMeasure11: " ",
        strMeasure12: " ",
        strMeasure13: " ",
        strMeasure14: "",
        strMeasure15: "",
        dateModified: "2016-02-03 15:26:58"
      },
      {
        idDrink: "12864",
        strDrink: "Apple Cider Punch #1",
        strVideo: null,
        strCategory: "Punch / Party Drink",
        strIBA: null,
        strAlcoholic: "Optional alcohol",
        strGlass: "Collins Glass",
        strInstructions: "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
        strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
        strIngredient1: "Apple cider",
        strIngredient2: "Brown sugar",
        strIngredient3: "Lemonade",
        strIngredient4: "Orange juice",
        strIngredient5: "Cloves",
        strIngredient6: "Allspice",
        strIngredient7: "Nutmeg",
        strIngredient8: "Cinnamon",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strMeasure1: "4 qt ",
        strMeasure2: "1 cup ",
        strMeasure3: "6 oz frozen ",
        strMeasure4: "6 oz frozen ",
        strMeasure5: "6 whole ",
        strMeasure6: "6 whole ",
        strMeasure7: "1 tsp ground ",
        strMeasure8: "3 sticks ",
        strMeasure9: " ",
        strMeasure10: " ",
        strMeasure11: " ",
        strMeasure12: " ",
        strMeasure13: " ",
        strMeasure14: "",
        strMeasure15: "",
        dateModified: "2016-02-03 15:26:58"
      },
      {
        idDrink: "12864",
        strDrink: "Apple Cider Punch #1",
        strVideo: null,
        strCategory: "Punch / Party Drink",
        strIBA: null,
        strAlcoholic: "Optional alcohol",
        strGlass: "Collins Glass",
        strInstructions: "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
        strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
        strIngredient1: "Apple cider",
        strIngredient2: "Brown sugar",
        strIngredient3: "Lemonade",
        strIngredient4: "Orange juice",
        strIngredient5: "Cloves",
        strIngredient6: "Allspice",
        strIngredient7: "Nutmeg",
        strIngredient8: "Cinnamon",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strMeasure1: "4 qt ",
        strMeasure2: "1 cup ",
        strMeasure3: "6 oz frozen ",
        strMeasure4: "6 oz frozen ",
        strMeasure5: "6 whole ",
        strMeasure6: "6 whole ",
        strMeasure7: "1 tsp ground ",
        strMeasure8: "3 sticks ",
        strMeasure9: " ",
        strMeasure10: " ",
        strMeasure11: " ",
        strMeasure12: " ",
        strMeasure13: " ",
        strMeasure14: "",
        strMeasure15: "",
        dateModified: "2016-02-03 15:26:58"
      },
      {
        idDrink: "12864",
        strDrink: "Apple Cider Punch #1",
        strVideo: null,
        strCategory: "Punch / Party Drink",
        strIBA: null,
        strAlcoholic: "Optional alcohol",
        strGlass: "Collins Glass",
        strInstructions: "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
        strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
        strIngredient1: "Apple cider",
        strIngredient2: "Brown sugar",
        strIngredient3: "Lemonade",
        strIngredient4: "Orange juice",
        strIngredient5: "Cloves",
        strIngredient6: "Allspice",
        strIngredient7: "Nutmeg",
        strIngredient8: "Cinnamon",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strMeasure1: "4 qt ",
        strMeasure2: "1 cup ",
        strMeasure3: "6 oz frozen ",
        strMeasure4: "6 oz frozen ",
        strMeasure5: "6 whole ",
        strMeasure6: "6 whole ",
        strMeasure7: "1 tsp ground ",
        strMeasure8: "3 sticks ",
        strMeasure9: " ",
        strMeasure10: " ",
        strMeasure11: " ",
        strMeasure12: " ",
        strMeasure13: " ",
        strMeasure14: "",
        strMeasure15: "",
        dateModified: "2016-02-03 15:26:58"
      },
      {
        idDrink: "12864",
        strDrink: "Apple Cider Punch #1",
        strVideo: null,
        strCategory: "Punch / Party Drink",
        strIBA: null,
        strAlcoholic: "Optional alcohol",
        strGlass: "Collins Glass",
        strInstructions: "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
        strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
        strIngredient1: "Apple cider",
        strIngredient2: "Brown sugar",
        strIngredient3: "Lemonade",
        strIngredient4: "Orange juice",
        strIngredient5: "Cloves",
        strIngredient6: "Allspice",
        strIngredient7: "Nutmeg",
        strIngredient8: "Cinnamon",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strMeasure1: "4 qt ",
        strMeasure2: "1 cup ",
        strMeasure3: "6 oz frozen ",
        strMeasure4: "6 oz frozen ",
        strMeasure5: "6 whole ",
        strMeasure6: "6 whole ",
        strMeasure7: "1 tsp ground ",
        strMeasure8: "3 sticks ",
        strMeasure9: " ",
        strMeasure10: " ",
        strMeasure11: " ",
        strMeasure12: " ",
        strMeasure13: " ",
        strMeasure14: "",
        strMeasure15: "",
        dateModified: "2016-02-03 15:26:58"
      },
      {
        idDrink: "12864",
        strDrink: "Apple Cider Punch #1",
        strVideo: null,
        strCategory: "Punch / Party Drink",
        strIBA: null,
        strAlcoholic: "Optional alcohol",
        strGlass: "Collins Glass",
        strInstructions: "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
        strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
        strIngredient1: "Apple cider",
        strIngredient2: "Brown sugar",
        strIngredient3: "Lemonade",
        strIngredient4: "Orange juice",
        strIngredient5: "Cloves",
        strIngredient6: "Allspice",
        strIngredient7: "Nutmeg",
        strIngredient8: "Cinnamon",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strMeasure1: "4 qt ",
        strMeasure2: "1 cup ",
        strMeasure3: "6 oz frozen ",
        strMeasure4: "6 oz frozen ",
        strMeasure5: "6 whole ",
        strMeasure6: "6 whole ",
        strMeasure7: "1 tsp ground ",
        strMeasure8: "3 sticks ",
        strMeasure9: " ",
        strMeasure10: " ",
        strMeasure11: " ",
        strMeasure12: " ",
        strMeasure13: " ",
        strMeasure14: "",
        strMeasure15: "",
        dateModified: "2016-02-03 15:26:58"
      }
    ]
}

export const mockCategoryOptionsResponse = {
  drinks: 
    [
      { strCategory: "Ordinary Drink" },
      { strCategory: "Cocktail" },
      { strCategory: "Milk / Float / Shake" },
      { strCategory: "Other/Unknown" },
      { strCategory: "Cocoa" },
      { strCategory: "Shot" },
      { strCategory: "Coffee / Tea" },
      { strCategory: "Homemade Liqueur" },
      { strCategory: "Punch / Party Drink" },
      { strCategory: "Beer" },
      { strCategory: "Soft Drink / Soda" }
  ]
}

export const mockFetchReject = 
  jest.fn().mockImplementation(() =>
    Promise.reject({
      message: "Something went wrong.",
      ok: false
    })
  );

export const mockInventory = 
  [
    "Grenadine",
    "Orange juice",
    "Tequila",
    "Amaretto"
  ]

export const mockIngredientsList = 
  [
    { strIngredient1: "151 proof rum" }, 
    { strIngredient1: "7-Up" }, 
    { strIngredient1: "Absinthe" }, 
    { strIngredient1: "Absolut Citron" }, 
    { strIngredient1: "Absolut Kurant" }, 
    { strIngredient1: "Absolut Vodka" }, 
    { strIngredient1: "Advocaat" }, 
    { strIngredient1: "Ale" }, 
    { strIngredient1: "Amaretto" }, 
    { strIngredient1: "Angelica root" }, 
    { strIngredient1: "Apple brandy" }, 
    { strIngredient1: "Apple cider" }, 
    { strIngredient1: "Apple juice" }, 
    { strIngredient1: "Applejack" }, 
    { strIngredient1: "Apricot brandy" }, 
    { strIngredient1: "Añejo rum" }, 
    { strIngredient1: "Bacardi Limon" }, 
    { strIngredient1: "Bailey's irish cream" }, 
    { strIngredient1: "Baileys irish cream" }, 
    { strIngredient1: "Banana liqueur" }, 
    { strIngredient1: "Beer" }, 
    { strIngredient1: "Berries" }, 
    { strIngredient1: "Bitters" }, 
    { strIngredient1: "Black Sambuca" }, 
    { strIngredient1: "Blackberry brandy" }, 
    { strIngredient1: "Blended Scotch" }, 
    { strIngredient1: "Blended whiskey" }, 
    { strIngredient1: "Blue Curacao" }, 
    { strIngredient1: "Bourbon" }, 
    { strIngredient1: "Brandy" }, 
    { strIngredient1: "Cachaca" }, 
    { strIngredient1: "Campari" }, 
    { strIngredient1: "Cantaloupe" }, 
    { strIngredient1: "Carbonated water" }, 
    { strIngredient1: "Chambord raspberry liqueur" }, 
    { strIngredient1: "Champagne" }, 
    { strIngredient1: "Cherry Heering" }, 
    { strIngredient1: "Cherry brandy" }, 
    { strIngredient1: "Chocolate" }, 
    { strIngredient1: "Chocolate ice-cream" }, 
    { strIngredient1: "Chocolate liqueur" }, 
    { strIngredient1: "Chocolate syrup" }, 
    { strIngredient1: "Cider" }, 
    { strIngredient1: "Coca-Cola" }, 
    { strIngredient1: "Cocoa powder" }, 
    { strIngredient1: "Coconut rum" }, 
    { strIngredient1: "Coffee" }, 
    { strIngredient1: "Coffee brandy" }, 
    { strIngredient1: "Coffee liqueur" }, 
    { strIngredient1: "Cognac" }, 
    { strIngredient1: "Cointreau" }, 
    { strIngredient1: "Corona" }, 
    { strIngredient1: "Cranberries" }, 
    { strIngredient1: "Cranberry juice" }, 
    { strIngredient1: "Cranberry vodka" }, 
    { strIngredient1: "Creme de Cacao" }, 
    { strIngredient1: "Creme de Cassis" }, 
    { strIngredient1: "Crown Royal" }, 
    { strIngredient1: "Dark rum" }, 
    { strIngredient1: "Dry Vermouth" }, 
    { strIngredient1: "Dubonnet Rouge" }, 
    { strIngredient1: "Egg" }, 
    { strIngredient1: "Egg yolk" }, 
    { strIngredient1: "Espresso" }, 
    { strIngredient1: "Everclear" }, 
    { strIngredient1: "Firewater" }, 
    { strIngredient1: "Frangelico" }, 
    { strIngredient1: "Fruit punch" }, 
    { strIngredient1: "Galliano" }, 
    { strIngredient1: "Gin" }, 
    { strIngredient1: "Ginger" }, 
    { strIngredient1: "Godiva liqueur" }, 
    { strIngredient1: "Goldschlager" }, 
    { strIngredient1: "Grand Marnier" }, 
    { strIngredient1: "Grape Soda" }, 
    { strIngredient1: "Grape juice" }, 
    { strIngredient1: "Grapefruit juice" }, 
    { strIngredient1: "Grapes" }, 
    { strIngredient1: "Green Chartreuse" }, 
    { strIngredient1: "Green Creme de Menthe" }, 
    { strIngredient1: "Grenadine" }, 
    { strIngredient1: "Guinness stout" }, 
    { strIngredient1: "Heavy cream" }, 
    { strIngredient1: "Hot Chocolate" }, 
    { strIngredient1: "Hot Damn" }, 
    { strIngredient1: "Ice" }, 
    { strIngredient1: "Irish cream" }, 
    { strIngredient1: "Irish whiskey" }, 
    { strIngredient1: "Jack Daniels" }, 
    { strIngredient1: "Jim Beam" }, 
    { strIngredient1: "Johnnie Walker" }, 
    { strIngredient1: "Jägermeister" }, 
    { strIngredient1: "Kahlua" }, 
    { strIngredient1: "Kiwi" }, 
    { strIngredient1: "Kiwi liqueur" }, 
    { strIngredient1: "Kool-Aid" }, 
    { strIngredient1: "Lager" }, 
    { strIngredient1: "Lemon" }, 
    { strIngredient1: "Lemon juice" }, 
    { strIngredient1: "Lemon peel" },
    { strIngredient1: "Lemon vodka"},
    { strIngredient1: "Lemonade" },
    { strIngredient1: "Light rum" },
    { strIngredient1: "Lime" },
    { strIngredient1: "Lime juice" },
    { strIngredient1: "Malibu rum" },
    { strIngredient1: "Mango" },
    { strIngredient1: "Maui" },
    { strIngredient1: "Mezcal" },
    { strIngredient1: "Midori melon liqueur" },
    { strIngredient1: "Milk" },
    { strIngredient1: "Mint" },
    { strIngredient1: "Orange" },
    { strIngredient1: "Orange bitters" },
    { strIngredient1: "Orange juice" },
    { strIngredient1: "Ouzo" },
    { strIngredient1: "Peach Vodka" },
    { strIngredient1: "Peach nectar" },
    { strIngredient1: "Peachtree schnapps" },
    { strIngredient1: "Peppermint schnapps" },
    { strIngredient1: "Pineapple juice" },
    { strIngredient1: "Pisco" },
    { strIngredient1: "Port" },
    { strIngredient1: "Prosecco" },
    { strIngredient1: "Raspberry vodka" },
    { strIngredient1: "Red wine" },
    { strIngredient1: "Ricard" },
    { strIngredient1: "Rum" },
    { strIngredient1: "Rye whiskey" },
    { strIngredient1: "Sambuca" },
    { strIngredient1: "Scotch" },
    { strIngredient1: "Sherry" },
    { strIngredient1: "Sloe gin" },
    { strIngredient1: "Sour mix" },
    { strIngredient1: "Southern Comfort" },
    { strIngredient1: "Spiced rum" },
    { strIngredient1: "Sprite" },
    { strIngredient1: "Strawberries" },
    { strIngredient1: "Strawberry schnapps" },
    { strIngredient1: "Sugar" },
    { strIngredient1: "Sugar syrup" },
    { strIngredient1: "Sweet Vermouth" },
    { strIngredient1: "Tea" },
    { strIngredient1: "Tequila" },
    { strIngredient1: "Tomato juice" },
    { strIngredient1: "Triple sec" },
    { strIngredient1: "Vanilla ice-cream" },
    { strIngredient1: "Vanilla vodka" },
    { strIngredient1: "Vermouth" },
    { strIngredient1: "Vodka" },
    { strIngredient1: "Water" },
    { strIngredient1: "Whiskey" },
    { strIngredient1: "Whisky" },
    { strIngredient1: "White Creme de Menthe" },
    { strIngredient1: "White Rum" },
    { strIngredient1: "Wild Turkey" },
    { strIngredient1: "Yoghurt" },
    { strIngredient1: "Yukon Jack" },
    { strIngredient1: "Zima" },
    { strIngredient1: "demerara Sugar" }
]

export const mockRecipesToBeFiltered =
  [
    {
      dateModified: "2016-02-03 15:47:54",
      idDrink: "15200",
      strAlcoholic: "Alcoholic",
      strCategory: "Ordinary Drink",
      strDrink: "A Day at the Beach",
      strDrinkThumb: "http://www.thecocktaildb.com/images/media/drink/trptts1454514474.jpg",
      strGlass: "Highball glass",
      strIBA: null,
      strIngredient1: "Coconut rum",
      strIngredient2: "Amaretto",
      strIngredient3: "Orange juice",
      strIngredient4: "Grenadine",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strInstructions: "Shake Rum, Amaretto, and Orange Juice in a shaker filled with ice. Strain over ice into a highball glass. Add Grenadine and garnish with a Pineapple Wedge and a Strawberry.",
      strMeasure1: "1 oz ",
      strMeasure2: "1/2 oz ",
      strMeasure3: "4 oz ",
      strMeasure4: "1/2 oz ",
      strMeasure5: " ",
      strMeasure6: " ",
      strMeasure7: " ",
      strMeasure8: " ",
      strMeasure9: " ",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strVideo: null
    },
    {
      dateModified: "2017-09-0:58" ,
      idDrink: "11025",
      strAlcoholic: "Alcoholic",
      strCategory: "Ordinary Drink",
      strDrink: "Amaretto And Cream",
      strDrinkThumb: "h://w hecocktaildb.com/images/media/drink/dj8n0r1504375018.jpg",
      strGlass: "Cocktail glass",
      strIBA: null,
      strIngredient1: "Amaretto",
      strIngredient2: "Light cream",
      strIngredient3: "",
      strIngredient4: "",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strInstructions: "Shake well with cracked ice, strain contents into a cocktail glass, and serve.",
      strMeasure1: "1 1/2 oz ",
      strMeasure2: "1 1/2 oz ",
      strMeasure3: " ",
      strMeasure4: " ",
      strMeasure5: " ",
      strMeasure6: " ",
      strMeasure7: " ",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strVideo: null
    },
    {
      dateModified: "2017-04-24 22:44:27",
      idDrink: "14578",
      strAlcoholic: "Alcoholic",
      strCategory: "Ordinary Drink",
      strDrink: "Amaretto Sunrise",
      strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/akcpsh1493070267.jpg",
      strGlass: "Collins Glass",
      strIBA: null,
      strIngredient1: "Amaretto",
      strIngredient2: "Orange juice",
      strIngredient3: "Grenadine",
      strIngredient4: "",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strInstructions: "Mix together the amaretto and orange juice. Pour into glass and then add the grenadine untill you see the sunrise.",
      strMeasure1: "1 cl ",
      strMeasure2: "4 oz ",
      strMeasure3: "1/4 cl ",
      strMeasure4: " ",
      strMeasure5: " ",
      strMeasure6: " ",
      strMeasure7: " ",
      strMeasure8: " ",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strVideo: null
    },
    {
      dateModified: "2016-02-03 15:15:46",
      idDrink: "14378",
      strAlcoholic: "Alcoholic",
      strCategory: "Beer",
      strDrink: "Lunch Box",
      strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/qywpvt1454512546.jpg",
      strGlass: "Pint glass",
      strIBA: null,
      strIngredient1: "Beer",
      strIngredient2: "Amaretto",
      strIngredient3: "Orange juice",
      strIngredient4: "",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strInstructions: "Fill a pint glass almost full with beer. Then fill the rest with orange juice (careful not to fill it to the top). Then take the shot of Amaretto and drop it in.",
      strMeasure1: "3/4 bottle ",
      strMeasure2: "1 shot ",
      strMeasure3: "1 oz ",
      strMeasure4: " ",
      strMeasure5: " ",
      strMeasure6: " ",
      strMeasure7: " ",
      strMeasure8: " ",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strVideo: null
    },
    {
      dateModified: "2016-09-08 15:23:45",
      idDrink: "13068",
      strAlcoholic: "Alcoholic",
      strCategory: "Shot",
      strDrink: "Brave Bull Shooter",
      strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/yrtypx1473344625.jpg",
      strGlass: "Shot glass",
      strIBA: null,
      strIngredient1: "Tequila",
      strIngredient2: "Tabasco sauce",
      strIngredient3: "",
      strIngredient4: "",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strInstructions: "Pour Tabasco into bottom of shot glass and fill with tequila.",
      strMeasure1: "1/2 oz ",
      strMeasure2: "1/2 oz ",
      strMeasure3: " ",
      strMeasure4: " ",
      strMeasure5: " ",
      strMeasure6: " ",
      strMeasure7: " ",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strVideo: null
    },
    {
      dateModified: "2016-12-04 19:18:23",
      idDrink: "13621",
      strAlcoholic: "Alcoholic",
      strCategory: "Cocktail",
      strDrink: "Tequila Sunrise",
      strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/quqyqp1480879103.jpg",
      strGlass: "Highball glass",
      strIBA: "Contemporary Classics",
      strIngredient1: "Tequila",
      strIngredient2: "Orange juice",
      strIngredient3: "Grenadine",
      strIngredient4: "",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strInstructions: "Pour the tequila and orange juice into glass over ice. Add the grenadine, which will sink to the bottom. Stir gently to create the sunrise effect. Garnish and serve.",
      strMeasure1: "2 measures ",
      strMeasure2: "",
      strMeasure3: "",
      strMeasure4: "",
      strMeasure5: "",
      strMeasure6: "",
      strMeasure7: "",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strVideo: null
    }
  ]

export const mockFilteredMenuRecipes =
  [
    {
      dateModified: "2017-09-0:58",
      idDrink: "11025",
      strAlcoholic: "Alcoholic",
      strCategory: "Ordinary Drink",
      strDrink: "Amaretto And Cream",
      strDrinkThumb: "h://w hecocktaildb.com/images/media/drink/dj8n0r1504375018.jpg",
      strGlass: "Cocktail glass",
      strIBA: null,
      strIngredient1: "Amaretto",
      strIngredient2: "Light cream",
      strIngredient3: "",
      strIngredient4: "",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strInstructions: "Shake well with cracked ice, strain contents into a cocktail glass, and serve.",
      strMeasure1: "1 1/2 oz ",
      strMeasure2: "1 1/2 oz ",
      strMeasure3: " ",
      strMeasure4: " ",
      strMeasure5: " ",
      strMeasure6: " ",
      strMeasure7: " ",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strVideo: null
    },
    {
      dateModified: "2017-04-24 22:44:27",
      idDrink: "14578",
      strAlcoholic: "Alcoholic",
      strCategory: "Ordinary Drink",
      strDrink: "Amaretto Sunrise",
      strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/akcpsh1493070267.jpg",
      strGlass: "Collins Glass",
      strIBA: null,
      strIngredient1: "Amaretto",
      strIngredient2: "Orange juice",
      strIngredient3: "Grenadine",
      strIngredient4: "",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strInstructions: "Mix together the amaretto and orange juice. Pour into glass and then add the grenadine untill you see the sunrise.",
      strMeasure1: "1 cl ",
      strMeasure2: "4 oz ",
      strMeasure3: "1/4 cl ",
      strMeasure4: " ",
      strMeasure5: " ",
      strMeasure6: " ",
      strMeasure7: " ",
      strMeasure8: " ",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strVideo: null
    },
    {
      dateModified: "2016-09-08 15:23:45",
      idDrink: "13068",
      strAlcoholic: "Alcoholic",
      strCategory: "Shot",
      strDrink: "Brave Bull Shooter",
      strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/yrtypx1473344625.jpg",
      strGlass: "Shot glass",
      strIBA: null,
      strIngredient1: "Tequila",
      strIngredient2: "Tabasco sauce",
      strIngredient3: "",
      strIngredient4: "",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strInstructions: "Pour Tabasco into bottom of shot glass and fill with tequila.",
      strMeasure1: "1/2 oz ",
      strMeasure2: "1/2 oz ",
      strMeasure3: " ",
      strMeasure4: " ",
      strMeasure5: " ",
      strMeasure6: " ",
      strMeasure7: " ",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strVideo: null
    },
    {
      dateModified: "2016-12-04 19:18:23",
      idDrink: "13621",
      strAlcoholic: "Alcoholic",
      strCategory: "Cocktail",
      strDrink: "Tequila Sunrise",
      strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/quqyqp1480879103.jpg",
      strGlass: "Highball glass",
      strIBA: "Contemporary Classics",
      strIngredient1: "Tequila",
      strIngredient2: "Orange juice",
      strIngredient3: "Grenadine",
      strIngredient4: "",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strInstructions: "Pour the tequila and orange juice into glass over ice. Add the grenadine, which will sink to the bottom. Stir gently to create the sunrise effect. Garnish and serve.",
      strMeasure1: "2 measures ",
      strMeasure2: "",
      strMeasure3: "",
      strMeasure4: "",
      strMeasure5: "",
      strMeasure6: "",
      strMeasure7: "",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strVideo: null
    }
  ]

